services:
  traefik:
    image: "traefik:3.3.6"
    container_name: "traefik-container"
    command:
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--log.level=INFO"
      - "--certificatesresolvers.leresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.leresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.leresolver.acme.storage=/traefik-volume/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-volume:/traefik-volume"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "traefik-network"
    restart: "unless-stopped"

  portainer-server:
    image: "portainer/portainer-ce:2.27.4"
    container_name: "portainer-server-container"
    command: "-H unix:///var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.rule=Host(`${EDGE_DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer-server-volume:/data"
    networks:
      - "traefik-network"
    restart: "unless-stopped"

volumes:
  traefik-volume:
    name: "traefik-volume"
  portainer-server-volume:
    name: "portainer-server-volume"

networks:
  traefik-network:
    name: "traefik-network"
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.32.0.0/16"
          ip_range: "172.32.1.0/24"
          gateway: "172.32.0.1"
