services:
  portainer-agent:
    image: "portainer/agent:2.27.4"
    container_name: "portainer-agent-container"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "/:/host"
      - "portainer-agent-volume:/data"
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - "EDGE=1"
      - "EDGE_ID=${EDGE_ID}"
      - "EDGE_KEY=${EDGE_KEY}"
      - "EDGE_INSECURE_POLL=1"

volumes:
  portainer-agent-volume:
    name: "portainer-agent-volume"
