name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push Docker images'
        required: false
        default: false
        type: boolean
      debian12_nodejs_typescript_salesforcecli:
        description: 'Build debian12-nodejs-typescript-salesforcecli'
        required: false
        default: false
        type: boolean
      debian12_nodejs_typescript_salesforcecli_chrome:
        description: 'Build debian12-nodejs-typescript-salesforcecli-chrome'
        required: false
        default: false
        type: boolean
      debian12_python_shadowsocksr:
        description: 'Build debian12-python-shadowsocksr'
        required: false
        default: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ fromJSON(github.event.inputs.push_images) }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image for debian12-nodejs-typescript-salesforcecli
        if: ${{ fromJSON(github.event.inputs.debian12_nodejs_typescript_salesforcecli) }}
        uses: docker/build-push-action@v6
        with:
          context: ./debian12-nodejs-typescript-salesforcecli
          file: ./debian12-nodejs-typescript-salesforcecli/Dockerfile
          push: ${{ fromJSON(github.event.inputs.push_images) }}
          tags: eric2369/debian12-nodejs-typescript-salesforcecli:${{ env.DATE }},eric2369/debian12-nodejs-typescript-salesforcecli:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image for debian12-nodejs-typescript-salesforcecli-chrome
        if: ${{ fromJSON(github.event.inputs.debian12_nodejs_typescript_salesforcecli_chrome) }}
        uses: docker/build-push-action@v6
        with:
          context: ./debian12-nodejs-typescript-salesforcecli-chrome
          file: ./debian12-nodejs-typescript-salesforcecli-chrome/Dockerfile
          push: ${{ fromJSON(github.event.inputs.push_images) }}
          tags: eric2369/debian12-nodejs-typescript-salesforcecli-chrome:${{ env.DATE }},eric2369/debian12-nodejs-typescript-salesforcecli-chrome:latest
          platforms: linux/amd64

      - name: Build and push Docker image for debian12-python-shadowsocksr
        if: ${{ fromJSON(github.event.inputs.debian12_python_shadowsocksr) }}
        uses: docker/build-push-action@v6
        with:
          context: ./debian12-python-shadowsocksr
          file: ./debian12-python-shadowsocksr/Dockerfile
          push: ${{ fromJSON(github.event.inputs.push_images) }}
          tags: eric2369/debian12-python-shadowsocksr:${{ env.DATE }},eric2369/debian12-python-shadowsocksr:latest
          platforms: linux/amd64,linux/arm64
