name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image for debian12-nodejs-typescript-salesforcecli
        uses: docker/build-push-action@v6
        with:
          context: ./debian12-nodejs-typescript-salesforcecli
          file: ./debian12-nodejs-typescript-salesforcecli/Dockerfile
          push: true
          tags: eric2369/debian12-nodejs-typescript-salesforcecli:${{ env.DATE }},eric2369/debian12-nodejs-typescript-salesforcecli:latest
          platforms: linux/amd64

      - name: Build and push Docker image for debian12-nodejs-typescript-salesforcecli-chrome
        uses: docker/build-push-action@v6
        with:
          context: ./debian12-nodejs-typescript-salesforcecli-chrome
          file: ./debian12-nodejs-typescript-salesforcecli-chrome/Dockerfile
          push: true
          tags: eric2369/debian12-nodejs-typescript-salesforcecli-chrome:${{ env.DATE }},eric2369/debian12-nodejs-typescript-salesforcecli-chrome:latest
          platforms: linux/amd64
